In [3]:
import pandas as pd
import numpy as np
from pandas import DataFrame

In [8]:
np.empty(5)

array([7.76421423e-312, 5.43966276e-321, 0.00000000e+000, 7.74528464e-312,
       7.76421423e-312])

In [11]:
b = np.random.random((3,3))
c = np.random.random((3,3))

In [20]:
b+=c
b

array([[0.82888403, 2.40251166, 2.57765299],
       [1.6452565 , 1.76490521, 0.39339438],
       [2.28284744, 1.16539394, 0.97391684]])

In [23]:
a = np.ones(2)
a

array([1., 1.])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
e = np.empty(5)
e

array([7.76393019e-312, 7.76402404e-312, 7.76402404e-312, 7.76421422e-312,
       5.98189404e-154])

In [47]:
ls = [12,34,56,678,8,99,44,455,45,12]
arr = np.array(ls)
arr

array([ 12,  34,  56, 678,   8,  99,  44, 455,  45,  12])

In [48]:
arr.shape
arr[2:5]
print(arr[3])
arr[1:3] = 44

678


In [49]:
arr_slice = arr[3:8]

In [50]:
arr_slice

array([678,   8,  99,  44, 455])

In [51]:
print(arr_slice[1:])
print(arr_slice[:])

[  8  99  44 455]
[678   8  99  44 455]


In [52]:
arr_slice[:] = -1

In [54]:
arr_slice
print(arr)

[12 44 44 -1 -1 -1 -1 -1 45 12]


In [55]:
arr2 = arr.copy()

In [57]:
arr2[3] = 55

In [58]:
arr2

array([12, 44, 44, 55, -1, -1, -1, -1, 45, 12])

# Array - Function

In [66]:
arr1 = np.random.randn(12)
arr2 = np.random.randn(12)
print(arr1)
print(arr2)

[ 0.29725228 -0.81285141  0.0068132   0.70021535  0.56670704  1.2039272
  0.03540596  1.46133816 -0.28860766 -0.46003106  0.50207614  0.69604568]
[ 1.00305179 -0.30106433  0.28954964  0.35021536  0.79097365  0.94826784
 -0.81329287 -1.06441003  1.03018264  1.66885985  0.73301471  0.51660033]


In [67]:
np.add(arr1,arr2)

array([ 1.30030407, -1.11391574,  0.29636284,  1.05043071,  1.35768069,
        2.15219503, -0.77788691,  0.39692814,  0.74157498,  1.20882879,
        1.23509085,  1.21264601])

In [69]:
np.minimum(arr1,arr2)

array([ 0.29725228, -0.81285141,  0.0068132 ,  0.35021536,  0.56670704,
        0.94826784, -0.81329287, -1.06441003, -0.28860766, -0.46003106,
        0.50207614,  0.51660033])

# Array Transpose

In [74]:
arr = np.arange(60).reshape(6,5,2)

In [79]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]],

       [[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]]])

In [80]:
arr.transpose()

array([[[ 0, 10, 20, 30, 40, 50],
        [ 2, 12, 22, 32, 42, 52],
        [ 4, 14, 24, 34, 44, 54],
        [ 6, 16, 26, 36, 46, 56],
        [ 8, 18, 28, 38, 48, 58]],

       [[ 1, 11, 21, 31, 41, 51],
        [ 3, 13, 23, 33, 43, 53],
        [ 5, 15, 25, 35, 45, 55],
        [ 7, 17, 27, 37, 47, 57],
        [ 9, 19, 29, 39, 49, 59]]])

# simple_stars

In [81]:
arr = np.random.randn(4,4)
arr

array([[ 0.02473463, -2.04613324, -1.18635557, -0.74955162],
       [-0.56488451, -0.85373401, -0.48122825, -0.31404661],
       [-1.88885738, -0.85624197,  1.43601323,  2.20250999],
       [-0.05922236,  0.49338999, -1.40037582,  1.23356467]])

In [84]:
arr.var()

1.3068422384047433

In [87]:
np.where(arr<0,0,arr)

array([[0.02473463, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.43601323, 2.20250999],
       [0.        , 0.49338999, 0.        , 1.23356467]])

In [89]:
arr.sort()
arr

array([[-2.04613324, -1.18635557, -0.74955162,  0.02473463],
       [-0.85373401, -0.56488451, -0.48122825, -0.31404661],
       [-1.88885738, -0.85624197,  1.43601323,  2.20250999],
       [-1.40037582, -0.05922236,  0.49338999,  1.23356467]])

In [94]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

o = np.append(a1,a2)
o

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [95]:
a = np.array([1,2,3,4,5])

b = np.array([1,3,2,4,5])

print(np.where(a == b))

(array([0, 3, 4], dtype=int64),)


In [97]:
a = np.array([[1,2,3],
              [4,5,6]])

o = np.tile(a, 10)

print(o)

[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


In [100]:
np.random.seed(123)

In [111]:
a = np.random.randint(0,10,size=(5,5))
a

array([[8, 9, 1, 0, 3],
       [1, 3, 4, 7, 6],
       [1, 4, 3, 3, 7],
       [6, 8, 6, 4, 4],
       [7, 0, 0, 9, 8]])

In [112]:
a = np.random.normal(size=(3,3))
a

array([[-0.65450815,  1.30157726, -1.56292586],
       [ 0.31314609, -0.10412192,  1.00767228],
       [-0.61307813, -0.91179701,  0.24276603]])

In [115]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

o = np.matmul(a,b)

print(o)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [118]:
c = a.T
c

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [121]:
angles = np.array([3.14, 3.14/2, 6.28])
print(angles)
sine_of_angles = np.sin(angles)
cos_of_angles = np.cos(angles)
print(cos_of_angles)
print('Sine of the given array of angles = ', sine_of_angles)

[3.14 1.57 6.28]
[-9.99998732e-01  7.96326711e-04  9.99994927e-01]
Sine of the given array of angles =  [ 0.00159265  0.99999968 -0.0031853 ]


In [123]:
array = np.array([10,1,5,2])
print(array)
indexes = np.argsort(array)

print(indexes)

[10  1  5  2]
[1 3 2 0]
